package ru.fanter.colorlife;

public enum ElementType {
	NONE, SPLITTER, COLOR_CHANGER, SHAPE_CHANGER,
	RECYCLER, DETECTOR_COLOR, DETECTOR_SHAPE, MERGER,
	RECEIVER, ARROW_UP, ARROW_DOWN, ARROW_RIGHT, ARROW_LEFT,
	LINE_ARROW;
}